In [1]:
import numpy as np
from scipy import stats

In [63]:
res = stats.binomtest(67, 100, 0.75, alternative = 'two-sided')
round(res.pvalue, 4)

0.0822

In [59]:
stats.binomtest?

Signature: stats.binomtest(k, n, p=0.5, alternative='two-sided')
Docstring:
Perform a test that the probability of success is p.

The binomial test [1]_ is a test of the null hypothesis that the
probability of success in a Bernoulli experiment is `p`.

Details of the test can be found in many texts on statistics, such
as section 24.5 of [2]_.

Parameters
----------
k : int
    The number of successes.
n : int
    The number of trials.
p : float, optional
    The hypothesized probability of success, i.e. the expected
    proportion of successes.  The value must be in the interval
    ``0 <= p <= 1``. The default value is ``p = 0.5``.
alternative : {'two-sided', 'greater', 'less'}, optional
    Indicates the alternative hypothesis. The default value is
    'two-sided'.

Returns
-------
result : `~scipy.stats._result_classes.BinomTestResult` instance
    The return value is an object with the following attributes:

    k : int
        The number of successes (copied from `binomtest` input

In [14]:
pines_data = []
with open('pines.txt') as fp:
    print(fp.readline())
    for line in fp:
        data = line.strip().split('\t')
        if not data:
            continue
        sn, we = float(data[0]), float(data[1])
        pines_data.append((sn, we))
pines_data = np.array(pines_data)

sn	we



In [23]:
pines_data

array([[200. ,   8.8],
       [199.3,  10. ],
       [193.6,  22.4],
       ...,
       [156.7, 155.3],
       [154.1, 150.8],
       [ 87.7, 200. ]])

In [28]:
min(pines_data[:, 0])

0.0

In [29]:
max(pines_data[:, 0])

200.0

In [30]:
min(pines_data[:, 1])

0.0

In [31]:
max(pines_data[:, 1])

200.0

In [32]:
bins_x = [x for x in range(0, 201, 40)]
bins_y = bins_x[:]

In [33]:
bins_x

[0, 40, 80, 120, 160, 200]

In [34]:
bins_y

[0, 40, 80, 120, 160, 200]

In [42]:
res = stats.binned_statistic_2d(pines_data[:, 0], pines_data[:, 1], None, 'count', bins=[bins_x, bins_y])
res

BinnedStatistic2dResult(statistic=array([[18., 26., 29., 25., 20.],
       [14., 12., 22., 34., 25.],
       [12., 24., 15., 50., 37.],
       [ 8., 19., 31., 50.,  7.],
       [ 7.,  8., 37., 27., 27.]]), x_edge=array([  0.,  40.,  80., 120., 160., 200.]), y_edge=array([  0.,  40.,  80., 120., 160., 200.]), binnumber=array([36, 36, 36, 36, 37, 37, 37, 37, 36, 36, 36, 29, 30, 29, 30, 29, 29,
       29, 29, 29, 22, 22, 22, 22, 22, 29, 30, 30, 23, 23, 22,  8,  8,  8,
        8,  8,  8,  8, 15, 15,  8, 15, 15,  9,  9,  9,  9,  9,  9,  9,  9,
        8,  8,  9,  9,  9,  8,  8,  8,  8,  9,  9, 16, 16, 17, 16, 17, 17,
       17,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 17, 17, 10, 10, 10, 10,
       10, 10, 10, 24, 24, 23, 23, 23, 23, 24, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 30, 23, 23, 23, 23, 30, 30, 23, 23, 30, 30, 31, 30, 30,
       30, 22, 22, 22, 15, 22, 22, 22, 15, 15, 16, 16, 15, 15, 15, 15, 15,
       15, 15, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,  8,  8,  8,
     

In [39]:
expected = pines_data.shape[0] / ((len(bins_x) - 1) * (len(bins_y) - 1))
expected

23.36

In [ ]:
expected_freqs

In [54]:
observed_freqs = res.statistic.reshape((res.statistic.shape[0] * res.statistic.shape[1],))
observed_freqs

array([18., 26., 29., 25., 20., 14., 12., 22., 34., 25., 12., 24., 15.,
       50., 37.,  8., 19., 31., 50.,  7.,  7.,  8., 37., 27., 27.])

In [52]:
expected_freqs = np.array([expected] * obserced_freqs.shape[0])
expected_freqs

array([23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36,
       23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36,
       23.36, 23.36, 23.36, 23.36, 23.36, 23.36, 23.36])

In [56]:
res = stats.chisquare(observed_freqs, expected_freqs, ddof = 1)
res

Power_divergenceResult(statistic=150.58904109589042, pvalue=9.87806178820889e-21)

In [58]:
round(res.statistic, 2)

150.59