In [17]:
import itertools
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.sandbox.stats.multicomp import multipletests 

In [3]:
auc_data = pd.read_csv('auc.txt', sep='\t')
auc_data

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0            adult (sample)  0.763   0.768    0.771      0.798
1             breast cancer  0.599   0.591    0.590      0.569
2   breast cancer wisconsin  0.954   0.971    0.968      0.967
3                       cmc  0.628   0.661    0.654      0.657
4                ionosphere  0.882   0.888    0.886      0.898
5                      iris  0.936   0.931    0.916      0.931
6           liver disorders  0.661   0.668    0.609      0.685
7               lung cancer  0.583   0.583    0.563      0.625
8              lymphography  0.775   0.838    0.866      0.875
9                  mushroom  1.000   1.000    1.000      1.000
10            primary tumor  0.940   0.962    0.965      0.962
11                    rheum  0.619   0.666    0.614      0.669
12                   voting  0.972   0.981    0.975      0.975
13                     wine  0.957   0.978    0.946      0.970

In [14]:
auc_comb = list(itertools.combinations(['C4.5', 'C4.5+m', 'C4.5+cf', 'C4.5+m+cf'], 2))

In [25]:
auc_wilcoxon = {}
for name1, name2 in auc_comb:
    res = stats.wilcoxon(auc_data[name1], auc_data[name2], mode='approx')
    auc_wilcoxon[name1, name2] = res

In [26]:
auc_wilcoxon

{('C4.5', 'C4.5+m'): WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963),
 ('C4.5', 'C4.5+cf'): WilcoxonResult(statistic=43.0, pvalue=0.861262330095348),
 ('C4.5',
  'C4.5+m+cf'): WilcoxonResult(statistic=11.0, pvalue=0.015874359307532084),
 ('C4.5+m',
  'C4.5+cf'): WilcoxonResult(statistic=18.0, pvalue=0.05432871367198416),
 ('C4.5+m',
  'C4.5+m+cf'): WilcoxonResult(statistic=22.0, pvalue=0.3278256758446406),
 ('C4.5+cf',
  'C4.5+m+cf'): WilcoxonResult(statistic=10.5, pvalue=0.025313519968766574)}

In [22]:
auc_reject, auc_p_corrected, auc_a1, auc_a2 = multipletests(
    [x.pvalue for x in auc_wilcoxon.values()], 
    alpha = 0.05, 
    method = 'holm',
)

In [20]:
auc_reject

array([False, False, False, False, False, False])

In [21]:
auc_p_corrected

array([0.0645428 , 0.86126233, 0.0793718 , 0.16298614, 0.65565135,
       0.10125408])

In [28]:
auc_reject, auc_p_corrected, auc_a1, auc_a2 = multipletests(
    [x.pvalue for x in auc_wilcoxon.values()], 
    alpha = 0.05, 
    method = 'fdr_bh',
)

In [29]:
auc_reject

array([ True, False,  True, False, False, False])

In [30]:
auc_p_corrected

array([0.04762308, 0.86126233, 0.04762308, 0.08149307, 0.39339081,
       0.05062704])