In [42]:
import pandas as pd
import numpy as np
from  sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, SCORERS
from sklearn.naive_bayes import MultinomialNB

In [9]:
with open('c5/SMSSpamCollection.txt') as fp:
    raw_data = [x.strip() for x in fp.readlines() if x.strip()]

In [10]:
data = []
for line in raw_data:
    y, x = line.split('\t', 1)
    data.append({
        'spam': 1 if y == 'spam' else 0,
        'text': x,
    })
data = pd.DataFrame(data)
data.head()

spam                                               text
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...
2     1  Free entry in 2 a wkly comp to win FA Cup fina...
3     0  U dun say so early hor... U c already then say...
4     0  Nah I don't think he goes to usf, he lives aro...

In [13]:
cv = CountVectorizer()
cv_default = cv.fit_transform(data.text)

In [25]:
est = LogisticRegression()
cv_results = cross_val_score(est, cv_default, data.spam, cv=10, scoring='f1')
cv_results

array([0.97297297, 0.89855072, 0.91549296, 0.95833333, 0.92957746,
       0.91176471, 0.92857143, 0.92857143, 0.91549296, 0.95172414])

In [54]:
with open('c5/SMSSpamCollection.answer1.txt', 'w') as fp:
    res = round(np.mean(cv_results), 1)
    fp.write(str(res))
res

0.9

In [35]:
cv_regresson = LogisticRegression(fit_intercept=False)
cv_regresson.fit(cv_default, data.spam)

LogisticRegression(fit_intercept=False)

In [36]:
messages = [
    'FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GB',
    'FreeMsg: Txt: claim your reward of 3 hours talk time',
    'Have you visited the last lecture on physics?',
    'Have you visited the last lecture on physics? Just buy this book and you will have all materials! Only 99$',
    'Only 99$',
]

task6_results = []
for msg in messages:
    dt = cv.transform([msg])
    res = cv_regresson.predict(dt)
    print(res, msg)
    task6_results.append(res[0])

[1] FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GB
[1] FreeMsg: Txt: claim your reward of 3 hours talk time
[0] Have you visited the last lecture on physics?
[0] Have you visited the last lecture on physics? Just buy this book and you will have all materials! Only 99$
[0] Only 99$


In [53]:
with open('c5/SMSSpamCollection.answer2.txt', 'w') as fp:
    res = ' '.join(str(x) for x in task6_results)
    fp.write(str(res))
res

'1 1 0 0 0'

In [37]:
cv22 = CountVectorizer(ngram_range=(2, 2))
cv22_data = cv22.fit_transform(data.text)

In [38]:
est = LogisticRegression()
cv22_results = cross_val_score(est, cv22_data, data.spam, cv=10, scoring='f1')
cv22_results

array([0.828125  , 0.8125    , 0.8372093 , 0.828125  , 0.84375   ,
       0.816     , 0.79674797, 0.7704918 , 0.7804878 , 0.85496183])

In [39]:
cv33 = CountVectorizer(ngram_range=(3, 3))
cv33_data = cv33.fit_transform(data.text)

cv13 = CountVectorizer(ngram_range=(1, 3))
cv13_data = cv13.fit_transform(data.text)

In [40]:
est = LogisticRegression()
cv33_results = cross_val_score(est, cv33_data, data.spam, cv=10, scoring='f1')
cv33_results

array([0.75      , 0.71794872, 0.71794872, 0.75      , 0.73504274,
       0.71304348, 0.71304348, 0.70689655, 0.69565217, 0.75      ])

In [41]:
est = LogisticRegression()
cv13_results = cross_val_score(est, cv13_data, data.spam, cv=10, scoring='f1')
cv13_results

array([0.94366197, 0.88888889, 0.92198582, 0.92198582, 0.9352518 ,
       0.91176471, 0.91970803, 0.92086331, 0.90780142, 0.95104895])

In [55]:
with open('c5/SMSSpamCollection.answer3.txt', 'w') as fp:
    res22 = round(np.mean(cv22_results), 2)
    res33 = round(np.mean(cv33_results), 2)
    res13 = round(np.mean(cv13_results), 2)

    res = f'{res22} {res33} {res13}'
    fp.write(str(res))
res

'0.82 0.72 0.92'

In [43]:
est = MultinomialNB()
cv22_nb_results = cross_val_score(est, cv22_data, data.spam, cv=10, scoring='f1')
cv22_nb_results

array([0.68202765, 0.64628821, 0.63559322, 0.62978723, 0.65740741,
       0.65116279, 0.63157895, 0.61538462, 0.63247863, 0.66972477])

In [44]:
est = MultinomialNB()
cv33_nb_results = cross_val_score(est, cv33_data, data.spam, cv=10, scoring='f1')
cv33_nb_results

array([0.39361702, 0.37659033, 0.390625  , 0.3649635 , 0.38797814,
       0.37597911, 0.36962025, 0.3718593 , 0.37593985, 0.37878788])

In [45]:
est = MultinomialNB()
cv13_nb_results = cross_val_score(est, cv13_data, data.spam, cv=10, scoring='f1')
cv13_nb_results

array([0.93081761, 0.9068323 , 0.8969697 , 0.88622754, 0.85542169,
       0.86956522, 0.86956522, 0.88484848, 0.86549708, 0.9125    ])

In [56]:
with open('c5/SMSSpamCollection.answer4.txt', 'w') as fp:
    res22 = round(np.mean(cv22_nb_results), 2)
    res33 = round(np.mean(cv33_nb_results), 2)
    res13 = round(np.mean(cv13_nb_results), 2)

    res = f'{res22} {res33} {res13}'
    fp.write(str(res))
res

'0.65 0.38 0.89'

In [46]:
ti13 = TfidfVectorizer(ngram_range=(1, 3))
ti13_data = ti13.fit_transform(data.text)

In [47]:
est = LogisticRegression()
ti13_results = cross_val_score(est, ti13_data, data.spam, cv=10, scoring='f1')
ti13_results

array([0.68421053, 0.66071429, 0.62385321, 0.64864865, 0.64220183,
       0.71304348, 0.54901961, 0.61111111, 0.59813084, 0.71794872])

In [57]:
with open('c5/SMSSpamCollection.answer5.txt', 'w') as fp:
    res = '-1'
    fp.write(str(res))
res

'-1'