In [54]:
import pandas as pd
import numpy as np
from nltk.corpus import movie_reviews
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from operator import itemgetter

In [2]:
negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')

In [3]:
negfeats = [movie_reviews.words(fileids=[f]) for f in negids]
posfeats = [movie_reviews.words(fileids=[f]) for f in posids]

In [4]:
data = []
for words in negfeats:
    data.append(dict(
        text=' '.join(words),
        positive=0,
    ))

for words in posfeats:
    data.append(dict(
        text=' '.join(words),
        positive=1,
    ))

data = pd.DataFrame(data)

In [5]:
data.head()

text  positive
0  plot : two teen couples go to a church party ,...         0
1  the happy bastard ' s quick movie review damn ...         0
2  it is movies like these that make a jaded movi...         0
3  " quest for camelot " is warner bros . ' first...         0
4  synopsis : a mentally unstable man undergoing ...         0

In [7]:
data.shape

(2000, 2)

In [8]:
with open('ans1.txt', 'w') as fp:
    fp.write(str(data.shape[0]))

In [9]:
pos_prop = data[data.positive == 1].shape[0] / data.shape[0]
pos_prop

0.5

In [10]:
with open('ans2.txt', 'w') as fp:
    fp.write(str(pos_prop))

In [12]:
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(data.text)
features.shape

(2000, 39659)

In [13]:
with open('ans3.txt', 'w') as fp:
    fp.write(str(features.shape[1]))

In [22]:
estimator = LogisticRegression()
acc_cv_result = cross_val_score(estimator, features, data.positive, scoring='accuracy')
acc_cv_result

/home/andre/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/andre/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.805 , 0.845 , 0.84  , 0.8725, 0.85  ])

In [50]:
mean_acc = round(np.mean(acc_cv_result), 4)
mean_acc

0.8425

In [51]:
with open('ans4.txt', 'w') as fp:
    fp.write(str(mean_acc))

In [23]:
estimator = LogisticRegression()
auc_cv_result = cross_val_score(estimator, features, data.positive, scoring='roc_auc')
auc_cv_result

/home/andre/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/andre/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.8988  , 0.91935 , 0.910975, 0.930075, 0.923025])

In [52]:
mean_auc = round(np.mean(auc_cv_result), 4)
mean_auc

0.9164

In [53]:
with open('ans5.txt', 'w') as fp:
    fp.write(str(mean_auc))

In [29]:
estimator.fit(features, data.positive)

/home/andre/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [33]:
estimator.coef_

array([[ 0.01163311, -0.01003717,  0.00050338, ..., -0.00820574,
         0.00093829, -0.00120051]])

In [58]:
est_features = []
feature_names = vectorizer.get_feature_names_out()
for idx, x in enumerate(estimator.coef_[0]):
    est_features.append((x, abs(x), idx, feature_names[idx]))

est_features.sort(key=itemgetter(1), reverse=True)
est_features

[(-0.8133723229331671, 0.8133723229331671, 2954, 'bad'),
 (-0.6407131430578675, 0.6407131430578675, 37056, 'unfortunately'),
 (-0.6025325053136557, 0.6025325053136557, 39195, 'worst'),
 (0.565784250747216, 0.565784250747216, 14159, 'fun'),
 (-0.5201758552810457, 0.5201758552810457, 24063, 'nothing'),
 (-0.4844350302324802, 0.4844350302324802, 38417, 'waste'),
 (-0.4771251337596662, 0.4771251337596662, 4425, 'boring'),
 (-0.4746374035639166, 0.4746374035639166, 30874, 'script'),
 (-0.4687274624573237, 0.4687274624573237, 24521, 'only'),
 (-0.4627921445385461, 0.4627921445385461, 2847, 'awful'),
 (0.46074505955128636, 0.46074505955128636, 15246, 'great'),
 (-0.44378029577670636, 0.44378029577670636, 26667, 'poor'),
 (0.4415111294894564, 0.4415111294894564, 2908, 'back'),
 (-0.4412926618337435, 0.4412926618337435, 26455, 'plot'),
 (-0.4332058824655825, 0.4332058824655825, 28376, 'reason'),
 (-0.4224811518846184, 0.4224811518846184, 20832, 'looks'),
 (-0.3971762242880211, 0.397176224288021

In [ ]:
with open('ans6.txt', 'w') as fp:
    fp.write(f'{est_features[0][-1]} {est_features[1][-1]}')